name: Build XMRig for Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          git \
          build-essential \
          cmake \
          automake \
          libtool \
          autoconf

    - name: Create build directory
      run: mkdir build

    - name: Build dependencies
      run: ./build_deps.sh
      working-directory: scripts

    - name: Configure CMake
      run: cmake .. -DXMRIG_DEPS=scripts/deps
      working-directory: build

    - name: Build XMRig
      run: make -j$(nproc)
      working-directory: build

    - name: Archive build
      uses: actions/upload-artifact@v4
      with:
        name: xmrig-ubuntu
        path: build/xmrig
